###########################################################################

#  ███████╗███╗   ██╗ █████╗ ██╗  ██╗███████╗███████╗██╗██╗     ███████╗
#  ██╔════╝████╗  ██║██╔══██╗██║ ██╔╝██╔════╝██╔════╝██║██║     ██╔════╝
#  ███████╗██╔██╗ ██║███████║█████╔╝ █████╗  █████╗  ██║██║     █████╗  
#  ╚════██║██║╚██╗██║██╔══██║██╔═██╗ ██╔══╝  ██╔══╝  ██║██║     ██╔══╝  
#  ███████║██║ ╚████║██║  ██║██║  ██╗███████╗██║     ██║███████╗███████╗
#  ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝╚══════╝
#
# This file is used to produce all the output files necessary to reproduce the paper's results.
# Workflow:
#   1. Import the project wide configuration for snakemake.
#   2. Include local rules to import the data set (will have to be changed to enhance reproducibility).
#   3. Include rules to process and analyse the data.
#   4. Include the master rule to produce the final output files.

###########################################################################

# Project wide configuration
configfile: "config/config.yaml"

# Include local rules
localrules: import_data, subset_vcf

# Include the other rules
include: "rules/setup.smk",
include: "rules/SLRfinder.smk",
include: "rules/plots.smk",
include: "rules/go.smk",
include: "rules/snp.smk",
include: "rules/misc.smk"

# Include a master rule to produce all the final output files
rule all:
    input:
        # Data
        "tmp/amphioxus/amphioxus.csv",
        "tmp/amphioxus/reference.list",
        # Setup
        expand("tmp/amphioxus/a15m75/amphioxus_{chromosomes}_a15m75.recode.vcf", chromosomes=config["CHROMOSOMES"]),
        expand("tmp/amphioxus/GenoLD.snp100/amphioxus_{chromosomes}_a15m75.geno.ld", chromosomes=config["CHROMOSOMES"]),
        "tmp/amphioxus/SLRfinder_scripts.R",
        "tmp/amphioxus/SLRfinder_functions.r",
        # SLRfinder
        "tmp/amphioxus/LD8.5cl20",
        # Plots
        "results/plots/gene_region.pdf",
        "results/plots/gene_region.png",
        "results/plots/karyotype.png",
        "results/plots/karyotype.pdf",
        "results/plots/heterozygosity_plot.png",
        "results/plots/heterozygosity_plot.pdf",
        "results/plots/heterozygosity_raw.png",
        "results/plots/heterozygosity_raw.pdf",
        "results/plots/combined_view.png",
        "results/plots/combined_view.pdf",
        "results/plots/manhattan_sexg.png",
        "results/plots/manhattan_sexg.pdf",
        "results/plots/manhattan_gc_adj.png",
        "results/plots/manhattan_gc_adj.pdf",
        "results/plots/manhattan_snp.png",
        "results/plots/manhattan_snp.pdf",
        "results/plots/legend_only.png",
        "results/plots/legend_only.pdf",
        "results/plots/legend_only.svg",
        # Miscellaneous
        "results/misc/haplotype_check_combined.tsv",
        "results/misc/haplotype_check_combined_summary.txt",
        "results/misc/ld_cluster_snps.txt",
        # Top SNPs
        "results/plots/top5_snps.json",
        # "results/snp/top5_snps_annotated.tsv",
        # "results/snp/chr4_snps.ann.vcf",
        "results/snp/top5_snp_effects.tsv",
        # Gene expression heatmaps
        "results/plots/heatmap_plot_flt1.png",
        "results/plots/heatmap_plot_flt1.pdf",
        "results/plots/heatmap_plot_flt1.svg",
        "results/plots/heatmap_plot_hao1.png",
        "results/plots/heatmap_plot_hao1.pdf",
        "results/plots/heatmap_plot_hao1.svg",
        "results/plots/heatmap_plot_hao1_flt1.png",
        "results/plots/heatmap_plot_hao1_flt1.pdf",
        "results/plots/heatmap_plot_hao1_flt1.svg",
        # Reproduced Het x PC1 plot
        "results/plots/het_pc1_plot.png",
        "results/plots/het_pc1_plot.pdf",
        "results/plots/het_pc1_plot.svg"
        # ========================================
        # "data/renamed/renamed.vcf.gz",
        # "data/renamed/renamed.gtf",
        # "data/annotation/GCA_927797965.1_BraLan3_genomic.fna.fai",
        # "results/snp/renamed.csq.vcf"
        # GO Enrichment
        # "data/annotation/all_geneids.txt",
        # "results/go/target_geneids.txt",
        # "data/go/gene2go_7740.tsv",
        # "data/go/go-basic.obo",
        # "results/go/go_enrichment.tsv"