###########################################################################

#  ███████╗███╗   ██╗ █████╗ ██╗  ██╗███████╗███████╗██╗██╗     ███████╗
#  ██╔════╝████╗  ██║██╔══██╗██║ ██╔╝██╔════╝██╔════╝██║██║     ██╔════╝
#  ███████╗██╔██╗ ██║███████║█████╔╝ █████╗  █████╗  ██║██║     █████╗  
#  ╚════██║██║╚██╗██║██╔══██║██╔═██╗ ██╔══╝  ██╔══╝  ██║██║     ██╔══╝  
#  ███████║██║ ╚████║██║  ██║██║  ██╗███████╗██║     ██║███████╗███████╗
#  ╚══════╝╚═╝  ╚═══╝╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝     ╚═╝╚══════╝╚══════╝
#
# This file is used to produce all the output files necessary to reproduce the paper's results.
# Workflow:
#   1. Import the project wide configuration for snakemake.
#   2. Include local rules to import the data set (will have to be changed to enhance reproducibility).
#   3. Include rules to process and analyse the data.
#   4. Include the master rule to produce the final output files.

###########################################################################

# Project wide configuration
configfile: "config/config.yaml"

# Include local rules
localrules: import_data, subset_vcf

# Include the other rules
include: "rules/setup.smk",
include: "rules/SLRfinder.smk",
include: "rules/plots.smk",
include: "rules/go.smk"

# Include a master rule to produce all the final output files
rule all:
    input:
        # Data
        "tmp/amphioxus/amphioxus.csv",
        "tmp/amphioxus/reference.list",
        # Setup
        expand("tmp/amphioxus/a15m75/amphioxus_{chromosomes}_a15m75.recode.vcf", chromosomes=config["CHROMOSOMES"]),
        expand("tmp/amphioxus/GenoLD.snp100/amphioxus_{chromosomes}_a15m75.geno.ld", chromosomes=config["CHROMOSOMES"]),
        "tmp/amphioxus/SLRfinder_scripts.R",
        "tmp/amphioxus/SLRfinder_functions.r",
        # SLRfinder
        "tmp/amphioxus/LD8.5cl20",
        # Plots
        "results/plots/gene_region.pdf",
        "results/plots/gene_region.png",
        "results/plots/karyotype.png",
        "results/plots/karyotype.pdf",
        "results/plots/heterozygosity_plot.png",
        "results/plots/heterozygosity_plot.pdf",
        "results/plots/heterozygosity_raw.png",
        "results/plots/heterozygosity_raw.pdf",
        "results/plots/combined_view.png",
        "results/plots/combined_view.pdf",
        "results/plots/manhattan_sexg.png",
        "results/plots/manhattan_sexg.pdf",
        "results/plots/manhattan_gc_adj.png",
        "results/plots/manhattan_gc_adj.pdf",
        "results/plots/manhattan_snp.png",
        "results/plots/manhattan_snp.pdf",
        "data/annotation/all_genes.txt",
        "results/go/genes_in_region.txt"