###########################################################################

#  ██████╗ ██████╗ ███╗   ██╗███████╗██╗ ██████╗ 
# ██╔════╝██╔═══██╗████╗  ██║██╔════╝██║██╔════╝ 
# ██║     ██║   ██║██╔██╗ ██║█████╗  ██║██║  ███╗
# ██║     ██║   ██║██║╚██╗██║██╔══╝  ██║██║   ██║
# ╚██████╗╚██████╔╝██║ ╚████║██║     ██║╚██████╔╝
#  ╚═════╝ ╚═════╝ ╚═╝  ╚═══╝╚═╝     ╚═╝ ╚═════╝ 
#
# Configuration file for the "foo-project".
# This file contains project-wide settings, such as thresholds, variables, and other
# parameters used in the Snakemake workflow.

###########################################################################

# Project name
name: amphioxus-slr

# Cluster configuration for slurm job submission
cluster: "sbatch -J {params.name} -N 1 \
    -o logs/.slurm/%x.out -e logs/.slurm/%x.err \
    --cpus-per-task={params.threads} \
    --mem={params.mem} -t {params.time}"

# Maximum number of jobs to run in parallel
jobs: 30  # Max parallel jobs

# Use Conda environments for the workflow
use-conda: true

# Thresholds or other variables
# threshold: 0.05  # Example threshold for statistical significance
# max_iterations: 1000  # Example maximum number of iterations for an algorithm
